version: "3.7"
services: 
    app: 
        image: node:12-alpine
        command: sh -c "yarn install && yarn start"
        working_dir: /app
        ports: 
            - "3000:3000"
        volumes: 
            - ./:/app